name: DeployStacks

on:
  push:
    branches:
      - master

env:
  CDK_VERSION: 2.2.0
  PIPENV_VENV_IN_PROJECT: "true"

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel awscli

      - name: Cache Python Files
        id: cache
        uses: actions/cache@v2
        with:
          path: aws-cdk/.venv
          key: ${{ runner.os }}-v1-${{ hashFiles('aws-cdk/Pipfile.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd aws-cdk && pipenv install && pipenv --venv

      - name: Install CDK
        run: |
          npm i -g aws-cdk@${CDK_VERSION}

      - name: CDK Deploy
        env:
          PYTHONPATH: ${{ github.workspace }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: "us-west-2"
          AWS_REGION: "us-west-2"
        run: |
          cd aws-cdk
          aws sts get-caller-identity
          pipenv run cdk deploy "*" --require-approval never
